steps:
  # Step 1: Build Docker image with SHA and latest tags - using cloudbuild yaml
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/calculadora-doses:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/calculadora-doses:latest'
      - '-f'
      - 'calculadora-insulina/Dockerfile'
      - './calculadora-insulina'

  # Step 2: Push Docker image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/calculadora-doses:$COMMIT_SHA'

  # Step 3: Push Docker image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/calculadora-doses:latest'

images:
  - 'gcr.io/$PROJECT_ID/calculadora-doses:latest'
  - 'gcr.io/$PROJECT_ID/calculadora-doses:$COMMIT_SHA'
