steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/$_GITHUB_OWNER/$_GITHUB_REPO:latest'
      - '-f'
      - 'calculadora-insulina/Dockerfile'
      - './calculadora-insulina'

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/github.com/$_GITHUB_OWNER/$_GITHUB_REPO:latest'

substitutions:
  _GITHUB_OWNER: 'drgustavoavelar'
  _GITHUB_REPO: 'calculadora-doses'

images:
  - 'gcr.io/$PROJECT_ID/github.com/$_GITHUB_OWNER/$_GITHUB_REPO:latest'

  # Step 3: Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - '--filename=calculadora-insulina'
  - '--image=gcr.io/$PROJECT_ID/github.com/$_GITHUB_OWNER/$_GITHUB_REPO:$COMMIT_SHA'
  - '--location=europe-west1'
  - '--namespace=default'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=europe-west1'
  - 'CLOUDSDK_RUN_PLATFORM=managed'
